resolver: lts-20.1

# User packages to be built.
packages:
- .
# Dependency packages to be pulled from upstream that are not in the resolver.
# These entries can reference officially published versions as well as
# forks / in-progress versions pinned to a git hash.
extra-deps:
- bitwise-1.0.0.1  # not included in the default resolver set
